version: '3'
services:
  similarity:
    container_name: similarity-docker
    build:
      context: ../food-truck-semantic
      dockerfile: food-truck-similarity.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - foodtruckdata:/var/lib/mysql
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=foodtruckdb
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=password
volumes:
  foodtruckdata: