version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - foodtruckdata:/var/lib/mysql
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=foodtruckdb
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=password
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-2
      - AWS_ACCESS_KEY_ID=development
      - AWS_SECRET_ACCESS_KEY=development
    ports:
      - "4572:4566"
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
volumes:
  foodtruckdata: