version: '3'
services:
  similarity:
    container_name: similarity-docker
    build:
      context: ../food-truck-semantic
      dockerfile: food-truck-similarity.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - MODULE_NAME=app
      - WORKERS_PER_CORE=1
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - foodtruckdata:/var/lib/mysql
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=foodtruckdb
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=password
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-2
      - AWS_ACCESS_KEY_ID=development
      - AWS_SECRET_ACCESS_KEY=development
    ports:
      - "4572:4566"
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
volumes:
  foodtruckdata: