name: Main workflow
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '14.0.2'
          java-package: jdk
          architecture: x64

      - name: Get Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      # Cache build files
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn Dependencies
        run: |
          cd food-truck-frontend
          yarn install --production=false

      - name: Test API
        run: |
          cd food-truck-api
          ./gradlew test

      - name: Test Frontend
        run: |
          cd food-truck-frontend
          yarn build
          yarn test --passWithNoTests

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Heroku CLI
        run: sudo curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Tag Dockerfiles
        run: |
          mv ./docker/food-truck-api.Dockerfile ./food-truck-api/Dockerfile.web
          mv ./docker/food-truck-frontend.Dockerfile ./food-truck-frontend/Dockerfile.web
          mv ./food-truck-semantic/food-truck-similarity.Dockerfile ./food-truck-semantic/Dockerfile.web

      - name: Push to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          cd ./food-truck-semantic
          heroku container:push -a spring-kings-similarity web --recursive
          heroku container:release -a spring-kings-similarity web
          heroku ps:scale -a spring-kings-similarity web=1

          cd ../food-truck-api
          heroku container:push -a spring-kings web --recursive
          heroku container:release -a spring-kings web
          heroku ps:scale -a spring-kings web=1

          cd ../food-truck-frontend
          heroku container:push -a spring-kings-frontend web --recursive
          heroku container:release -a spring-kings-frontend web
