name: Main workflow
on: [push, merge]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '14.0.2'
          java-package: jdk
          architecture: x64

      - name: Get Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      # Cache build files
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn Dependencies
        run: |
          cd food-truck-frontend
          yarn install --production=false

      - name: Test API
        run: |
          cd food-truck-api
          ./gradlew test

      - name: Test Frontend
        run: |
          cd food-truck-frontend
          yarn test --passWithNoTests
