name: Main workflow
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '14.0.2'
          java-package: jdk
          architecture: x64

      - name: Get Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      # Cache build files
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn Dependencies
        run: |
          cd food-truck-frontend
          yarn install --production=false

      - name: Test API
        run: |
          cd food-truck-api
          ./gradlew test

      - name: Test Frontend
        run: |
          cd food-truck-frontend
          yarn test --passWithNoTests

  #deploy:
  #  name:  Dispatch Deploy Workflow
  #  runs-on: ubuntu-latest
  #  needs: test
  #  steps:
  #    - name: Dispatch Repository
  #      uses: peter-evans/repository-dispatch@v1
  #      if: github.ref == 'refs/heads/master'
  #      with:
  #        token: ${{ secrets.GITHUB_TOKEN }}
  #        repository: Spring-Kings/food-truck-finder
  #        event-type: deploy

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Heroku CLI
        run: sudo curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Push to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          mv ./docker/food-truck-api.Dockerfile ./docker/food-truck-api.Dockerfile.web
          mv ./docker/food-truck-frontend.Dockerfile ./docker/food-truck-frontend.Dockerfile.web
          heroku container:push --recursive
